markdown        : kramdown
remote_theme    : pmarsceill/just-the-docs
#theme           : just-the-docs
logo            : "imgs/brkraw_logo.png"
aux_links       :
  "BrkRaw on GitHub":
    - "//github.com/brkraw/bruker"

heading_anchors : true
footer_content  : "Copyrignt &copy; 2019-2020 SungHo Lee. Distributed by an
  <a href=\"https://github.com/brkraw/bruker/LICENSE\">GNU General Public License v3.0</a>"

color_scheme    : nil
